### ISSUE TITLE
Can't move at all on mounts

### ISSUE THREAD

**Issue by razethion** [IoIxD/Cobblemounts#13]
We just loaded this onto our server with the BigChadGuys+ modpack, and we can mount pokemon but they don't move at all. I tried with the default config and the generic whitelist one provided on the mod download page.

When trying to walk, some mobs do show their walking animation (like charmeleon)

There's no error logs in the server console and I don't notice any weird behavior. I'm not sure where to start with providing further issue so any guidance or things to check would be great!

**Comment by IoIxD** [comment]
![Screenshot_20240103-085048.png](https://github.com/IoIxD/Cobblemounts/assets/30945097/6307a074-234a-43f7-a130-aa78a4948a58)

Can you try it without the mod that adds these planes/trains/automobiles?

**Comment by razethion** [comment]
> Do you have the mod on both the client and the server? It now requires both.

I have not yet, let me try that

**Comment by razethion** [comment]
> Do you have the mod on both the client and the server? It now requires both.

That was it. Having it client side fixes it
