### ISSUE TITLE
Separate Whitelist/Blacklist for flying and swimming, regardless of typing.

### ISSUE THREAD

**Issue by larsdude7** [IoIxD/Cobblemounts#18]
As the title suggests, there should be a separate list that allows you to allow and/or disallow certain pokemon from being able to fly or swim.
There are several pokemon that can fly or swim, that are not flying or water types, and vice versa. For example:

Gyarados and Dodrio are flying-types that should be rideable based on their size, but should not be able to fly.
The inverse is a little less common, but Latios/Latias come to mind as fliers that are not actually flying types.

The option for water would be nice to have as well, especially considering the crazy amounts of non-water types that learn surf in the games. Might not make the most sense, but the option would be nice.

**Comment by IoIxD** [comment]
Flying was already in, swimming was just dtone.
