### ISSUE TITLE
Can't configure speed and water mounts are flying

### ISSUE THREAD

**Issue by Crauford1** [IoIxD/Cobblemounts#27]
As the title says, all mounts are super speedy (which is so op it takes out the fun), and  water mounts (such as Gyarados) are also capable of flying (at high speeds as well). I tried configuring the file, using the code shared on the main page which whitelists only POkemon that makes sense, but with no success. Any help is appreciated.

**Comment by IoIxD** [comment]
The speed scaling badly was just fixed.

Cannot reproduce the water mounts issue; Gyarados is a Flying type and thus this is intended behavior.
