### ISSUE TITLE
WTF is this the Cobblemount update 

### ISSUE THREAD

**Issue by Djemtheman05** [IoIxD/Cobblemounts#33]
Cobblemounts 1.3.0 has some serious multiple bugs.

1: all the pokemon go at the speed of light on the ground.
2: changing the config and saving + restarting + reloading it ingame does not work.
3: flying pokemon stay midair on the same position if you dismount.

**Comment by IoIxD** [comment]
This update changed the config. You need to delete it to regenerate it, and this will fix your problems.
