### ISSUE TITLE
how do you even use the config

### ISSUE THREAD

**Issue by Mcnugggget** [IoIxD/Cobblemounts#38]
i want to blacklist certain pokemon but when ever I try my game crashes or mor specifically the mountable and unmountable list

**Comment by IoIxD** [comment]
Hi, can you post your config and the crash?

**Comment by Mcnugggget** [comment]
I was interested on how to use it

[cid:255a0d77-3dd8-41e8-a462-532ec12cee3a]
What do you add to the list area
I tried making it so i couldnt mount a specific pokmon[cid:8d1ca41b-e6f5-4bb0-ae3b-52bfea4f359f]
________________________________

**Comment by IoIxD** [comment]
You add Pokemon names to the list area. You say your game crashes, what are you adding?

**Comment by Mcnugggget** [comment]
Pokemon names
________________________________
