### ISSUE TITLE
Console overflowing with information, perhaps a toggle to turn it off?

### ISSUE THREAD

**Issue by Ralsey** [IoIxD/Cobblemounts#8]
First of all! I want to say thank you so much for updating it so quickly! You are a beast - this in respond to the previous ticket.
But here I am! XD Once again with a ticket.

There should be a toggle in the config or something to disable updates in the console. It overflows with updates if walking around

**Comment by IoIxD** [comment]
There shouldn't be any updates in the console if you're on the latest version. What are you seeing?

**Comment by Ralsey** [comment]
![image](https://github.com/IoIxD/Cobblemounts/assets/45522071/b55afe5c-da51-4a09-83bb-20d832ed0196)
a lot of stuff, is this perhaps another mod interacting with yours?

**Comment by Ralsey** [comment]
Oh apperently I didn't see the update.. Boop! Sorry, thx again
